name: schedule task

on:
  push:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/2 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: running
        run: |
          echo "running"
          ping 4.2.2.2
